### ISSUE TITLE
Install formula fails

### ISSUE THREAD

**Issue by compwright** [pigoz/homebrew-mplayer2#10]
I tried to install, following the [instructions](https://github.com/pigoz/homebrew-mplayer2), and got this error. Is this a bug, or did I do something wrong?

```
$ brew install --HEAD pigoz/mplayer2/mplayer2
Error: undefined local variable or method `build' for Mplayer2:Class
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/bug-fixing-checklist
/usr/local/Library/Taps/pigoz-mplayer2/Formula/mplayer2.rb:4:in `libav?'
/usr/local/Library/Taps/pigoz-mplayer2/Formula/mplayer2.rb:43
/usr/local/Library/Homebrew/formula.rb:378:in `require'
/usr/local/Library/Homebrew/formula.rb:378:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:14:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:14:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:14:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:20:in `install'
/usr/local/bin/brew:83:in `send'
/usr/local/bin/brew:83
```

**Comment by pigoz** [comment]
hello, looks like your homebrew is not up to date... let me know if updating solves this.

**Comment by compwright** [comment]
Thanks for the quick response! That did indeed fix it. Wouldn't hurt to mention the need to update in the installation instructions.
