### ISSUE TITLE
Install error: undefined method `libav?`

### ISSUE THREAD

**Issue by wffurr** [pigoz/homebrew-mplayer2#17]
Following instructions on the main page, I get the following:

```
wfurr@wfurr-macbookair:~$ brew tap pigoz/mplayer2
Cloning into '/Users/wfurr/homebrew/Library/Taps/pigoz/homebrew-mplayer2'...
remote: Counting objects: 181, done.
remote: Total 181 (delta 0), reused 0 (delta 0), pack-reused 181
Receiving objects: 100% (181/181), 24.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (50/50), done.
Checking connectivity... done.
Warning: Could not create link for pigoz/mplayer2/libav, as it
conflicts with Homebrew/homebrew/libav. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install pigoz/mplayer2/libav
Tapped 2 formulae

wfurr@wfurr-macbookair:~$ brew install mplayer2
Error: undefined method `libav?' for Formulary::Formulae::Mplayer2:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/wfurr/homebrew/Library/Taps/pigoz/homebrew-mplayer2/Formula/mplayer2.rb:70:in `<class:Mplayer2>'
/Users/wfurr/homebrew/Library/Taps/pigoz/homebrew-mplayer2/Formula/mplayer2.rb:55:in `load_file'
/Users/wfurr/homebrew/Library/Homebrew/formulary.rb:92:in `module_eval'
/Users/wfurr/homebrew/Library/Homebrew/formulary.rb:92:in `load_file'
/Users/wfurr/homebrew/Library/Homebrew/formulary.rb:82:in `klass'
/Users/wfurr/homebrew/Library/Homebrew/formulary.rb:71:in `get_formula'
/Users/wfurr/homebrew/Library/Homebrew/formulary.rb:200:in `factory'
/Users/wfurr/homebrew/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/Users/wfurr/homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/Users/wfurr/homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/Users/wfurr/homebrew/Library/Homebrew/cmd/install.rb:41:in `install'
/Users/wfurr/homebrew/Library/brew.rb:140:in `<main>'

wfurr@wfurr-macbookair:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
Error: Failed to import: mplayer2
undefined method `libav?' for Formulary::Formulae::Mplayer2:Class

wfurr@wfurr-macbookair:~$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

Even `brew gist-logs mplayer2` fails on the same error.

**Comment by pigoz** [comment]
This is not really maintained anymore. Should add a notice in the README.

All the original mplayer2 has moved to mpv (which has a maintained homebrew formula). I strongly suggest you use that instead.

http://mpv.io
https://github.com/mpv-player
